# Generated by Django 4.2.2 on 2023-06-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Customer Inquiry', 'verbose_name_plural': 'Customer Inquiries'},
        ),
    ]
