# Generated by Django 4.2.2 on 2023-06-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='ordering',
            field=models.IntegerField(default=1),
        ),
    ]
