# Generated by Django 4.2.2 on 2023-06-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='address',
            field=models.TextField(),
        ),
    ]
