# Generated by Django 4.2.2 on 2023-06-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(help_text='1920*1280 px', upload_to='banner')),
                ('thumbnail', models.ImageField(upload_to='banner')),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('button_name', models.CharField(max_length=255)),
                ('button_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner Setting',
            },
        ),
    ]
