# Generated by Django 4.2.2 on 2023-06-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Footer',
            new_name='FooterInfo',
        ),
    ]
