# Generated by Django 4.2.2 on 2023-06-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_rename_footer_footerinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerinfo',
            options={'verbose_name': 'Footer Info', 'verbose_name_plural': 'Footer Info'},
        ),
    ]
