# Generated by Django 4.2.2 on 2023-06-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('meta_keyword', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
    ]
